version: '3.8'

services:
  db:
    image: postgres
    container_name: nodejs-pg
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  node:
    container_name: node
    build:
      context: .
    command: npm run nodemon
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - db
    ports:
      - '3000:3000'