version: '3.8'

services:
  db:
    image: postgres
    container_name: ${DB_HOST}
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  node:
    container_name: node-malte
    build:
      context: .
    command: npm run start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - db
    ports:
      - '3000:3000'