name: CD-preprod

on:
  push:
    branches:  [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_APP_PREPROD}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          remote_branch: "develop"